delete from group_authorities;
delete from authorities;
delete from group_users;
delete from groups;
delete from password_histories;
delete from memberships;
delete from tokens;
delete from users;
delete from password_policies;
delete from token_policies;
delete from applications;
alter table applications auto_increment=1;
alter table authorities auto_increment=1;
alter table groups auto_increment=1;
alter table password_histories auto_increment=1;
alter table roles auto_increment=1;
alter table users auto_increment=1;
commit;