insert into applications(ID,NAME,DESCRIPTION,creation_date,last_update_date,version) VALUES (3001,'Test Application','This application is used for testing.',current_timestamp(),current_timestamp(),1);
insert into password_policies(MAXIMUM_INVALID_PASSWORD_ATTEMPTS, MAXIMUM_PASSWORD_AGE, MAXIMUM_PASSWORD_LENGTH, MINIMUM_SPECIAL_CHARACTERS, MINIMUM_PASSWORD_AGE, MINIMUM_PASSWORD_LENGTH, PASSWORD_ATTEMPT_WINDOW, PASSWORD_HISTORY_LENGTH, APPLICATION_ID,MINIMUM_LOWERCASE_CHARACTERS,MINIMUM_UPPERCASE_CHARACTERS,MINIMUM_NUMERIC) VALUES (5, 30, 25, 1, 0, 7, 10, 10, 3001,1,1,1);
insert into token_policies(APPLICATION_ID,MAXIMUM_AGE) VALUES (3001,30);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3001,'Sample Group 3001','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3002,'Sample Group 3002','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3003,'Sample Group 3003','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3004,'Sample Group 3004','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3005,'Sample Group 3005','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3001,'Authority 1','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3002,'Authority 2','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3003,'Authority 3','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3004,'Authority 4','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3005,'Authority 5','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3006,'Authority 6','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3007,'Authority 7','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3008,'Authority 8','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3009,'Authority 9','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) VALUES (3010,'Authority 10','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3002,3003);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3003,3006);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3003,3007);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3003,3008);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3004,3006);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3004,3007);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) VALUES (3005,3009);
commit;