-- -----------------------------------------------------
-- Table `applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applications` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME` (`NAME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `applications_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applications_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `LOCKOUT_POLICY_ID` BIGINT(20) NULL DEFAULT NULL,
  `LOGIN_POLICY_ID` BIGINT(20) NULL DEFAULT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PASSWORD_POLICY_ID` BIGINT(20) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `authorities` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UNQ_AUTHORITIES_0` (`APPLICATION_ID` ASC, `NAME` ASC),
  CONSTRAINT `FK_AUTHORITIES_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `authorities_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `authorities_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UNQ_GROUPS_0` (`APPLICATION_ID` ASC, `NAME` ASC),
  CONSTRAINT `FK_GROUPS_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group_authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_authorities` (
  `GROUP_ID` BIGINT(20) NOT NULL,
  `AUTHORITY_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`GROUP_ID`, `AUTHORITY_ID`),
  INDEX `FK_GROUP_AUTHORITIES_AUTHORITY_ID` (`AUTHORITY_ID` ASC),
  CONSTRAINT `FK_GROUP_AUTHORITIES_AUTHORITY_ID`
    FOREIGN KEY (`AUTHORITY_ID`)
    REFERENCES `authorities` (`ID`),
  CONSTRAINT `FK_GROUP_AUTHORITIES_GROUP_ID`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `groups` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_ACTIVITY_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UNQ_USERS_0` (`APPLICATION_ID` ASC, `USER_NAME` ASC),
  CONSTRAINT `FK_USERS_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_users` (
  `GROUP_ID` BIGINT(20) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`GROUP_ID`, `USER_ID`),
  INDEX `FK_GROUP_USERS_USER_ID` (`USER_ID` ASC),
  CONSTRAINT `FK_GROUP_USERS_GROUP_ID`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `groups` (`ID`),
  CONSTRAINT `FK_GROUP_USERS_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `users` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groups_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lockout_policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockout_policies` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ATTEMPT_WINDOW` SMALLINT(6) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DURATION` INT(11) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `RESET_TIME` INT(11) NULL DEFAULT NULL,
  `THRESHOLD` SMALLINT(6) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `APPLICATION_ID` (`APPLICATION_ID` ASC),
  CONSTRAINT `FK_LOCKOUT_POLICIES_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lockout_policies_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockout_policies_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NULL DEFAULT NULL,
  `ATTEMPT_WINDOW` SMALLINT(6) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DURATION` INT(11) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `RESET_TIME` INT(11) NULL DEFAULT NULL,
  `THRESHOLD` SMALLINT(6) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `memberships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memberships` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `ENABLED` TINYINT(1) NULL DEFAULT '0',
  `ENCRYPTED` TINYINT(1) NULL DEFAULT '0',
  `FAILED_PWD_ATMPT_CNT` SMALLINT(6) NULL DEFAULT NULL,
  `FAILED_PWD_ATMPT_WIN_START` DATETIME NULL DEFAULT NULL,
  `FAILED_REVRY_ATMPT_CNT` SMALLINT(6) NULL DEFAULT NULL,
  `FAILED_REVRY_ATMPT_WIN_START` DATETIME NULL DEFAULT NULL,
  `LAST_LOCK_OUT_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_PWD_CHANGE_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `LOCKED` TINYINT(1) NULL DEFAULT '0',
  `PASSWORD` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_ID` (`USER_ID` ASC),
  CONSTRAINT `FK_MEMBERSHIPS_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `users` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `login_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_histories` (
  `LOGIN_DATE` DATETIME NOT NULL,
  `HISTORY_ID` INT(11) NOT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`HISTORY_ID`, `MEMBERSHIP_ID`),
  INDEX `FK_LOGIN_HISTORIES_MEMBERSHIP_ID` (`MEMBERSHIP_ID` ASC),
  CONSTRAINT `FK_LOGIN_HISTORIES_MEMBERSHIP_ID`
    FOREIGN KEY (`MEMBERSHIP_ID`)
    REFERENCES `memberships` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `login_policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_policies` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `THRESHOLD` SMALLINT(6) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `APPLICATION_ID` (`APPLICATION_ID` ASC),
  CONSTRAINT `FK_LOGIN_POLICIES_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `login_policies_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_policies_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NULL DEFAULT NULL,
  `CREATIONDATE` DATETIME NULL DEFAULT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LASTUPDATEDATE` DATETIME NULL DEFAULT NULL,
  `THRESHOLD` SMALLINT(6) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITEOPERATION` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `memberships_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memberships_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `ENABLED` TINYINT(1) NULL DEFAULT '0',
  `ENCRYPTED` TINYINT(1) NULL DEFAULT '0',
  `FAILED_PWD_ATMPT_CNT` SMALLINT(6) NULL DEFAULT NULL,
  `FAILED_PWD_ATMPT_WIN_START` DATETIME NULL DEFAULT NULL,
  `FAILED_REVRY_ATMPT_CNT` SMALLINT(6) NULL DEFAULT NULL,
  `FAILED_REVRY_ATMPT_WIN_START` DATETIME NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_LOCK_OUT_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_PWD_CHANGE_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `LOCKED` TINYINT(1) NULL DEFAULT '0',
  `PASSWORD` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `password_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_histories` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CHANGE_DATE` DATETIME NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PASSWORD_HISTORIES_MEMBERSHIP_ID` (`MEMBERSHIP_ID` ASC),
  CONSTRAINT `FK_PASSWORD_HISTORIES_MEMBERSHIP_ID`
    FOREIGN KEY (`MEMBERSHIP_ID`)
    REFERENCES `memberships` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `password_histories_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_histories_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CHANGE_DATE` DATETIME NULL DEFAULT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `password_policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_policies` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `HISTORY_THRESHOLD` SMALLINT(6) NOT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `MAX_AGE` SMALLINT(6) NOT NULL,
  `MAX_LENGTH` SMALLINT(6) NOT NULL,
  `MIN_AGE` SMALLINT(6) NOT NULL,
  `MIN_LENGTH` SMALLINT(6) NOT NULL,
  `MIN_LOWERCASE_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `MIN_NUMERIC_COUNT` SMALLINT(6) NOT NULL,
  `MIN_SPECIAL_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `MIN_UPPERCASE_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `APPLICATION_ID` (`APPLICATION_ID` ASC),
  CONSTRAINT `FK_PASSWORD_POLICIES_APPLICATION_ID`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `applications` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `password_policies_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_policies_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NULL DEFAULT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `HISTORY_THRESHOLD` SMALLINT(6) NOT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `MAX_AGE` SMALLINT(6) NOT NULL,
  `MAX_LENGTH` SMALLINT(6) NOT NULL,
  `MIN_AGE` SMALLINT(6) NOT NULL,
  `MIN_LENGTH` SMALLINT(6) NOT NULL,
  `MIN_LOWERCASE_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `MIN_NUMERIC_COUNT` SMALLINT(6) NOT NULL,
  `MIN_SPECIAL_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `MIN_UPPERCASE_CHARS_COUNT` SMALLINT(6) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recovery_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recovery_information` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ANSWER` VARCHAR(255) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `ENCRYPTED` TINYINT(1) NULL DEFAULT '0',
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `QUESTION` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_RECOVERY_INFORMATION_MEMBERSHIP_ID` (`MEMBERSHIP_ID` ASC),
  CONSTRAINT `FK_RECOVERY_INFORMATION_MEMBERSHIP_ID`
    FOREIGN KEY (`MEMBERSHIP_ID`)
    REFERENCES `memberships` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recovery_information_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recovery_information_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ANSWER` VARCHAR(255) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `ENCRYPTED` TINYINT(1) NULL DEFAULT '0',
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NOT NULL,
  `QUESTION` VARCHAR(255) NOT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user_authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authorities` (
  `AUTHORITY_ID` BIGINT(20) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`AUTHORITY_ID`, `USER_ID`),
  INDEX `FK_USER_AUTHORITIES_USER_ID` (`USER_ID` ASC),
  CONSTRAINT `FK_USER_AUTHORITIES_AUTHORITY_ID`
    FOREIGN KEY (`AUTHORITY_ID`)
    REFERENCES `authorities` (`ID`),
  CONSTRAINT `FK_USER_AUTHORITIES_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `users` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `users_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_audit` (
  `AUDIT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `CREATOR` VARCHAR(255) NULL DEFAULT NULL,
  `ID` BIGINT(20) NULL DEFAULT NULL,
  `LAST_ACTIVITY_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` DATETIME NOT NULL,
  `MEMBERSHIP_ID` BIGINT(20) NULL DEFAULT NULL,
  `UPDATER` VARCHAR(255) NULL DEFAULT NULL,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `VERSION` BIGINT(20) NULL DEFAULT NULL,
  `WRITE_OPERATION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
