insert into applications(ID,NAME,DESCRIPTION,creation_date,last_update_date,version) values (3001,'Test Application 1','This application is used for testing.',current_timestamp(),current_timestamp(),1);
insert into password_policies(MAX_AGE, MAX_LENGTH, MIN_SPECIAL_CHARS_COUNT, MIN_AGE, MIN_LENGTH, HISTORY_THRESHOLD, APPLICATION_ID,MIN_LOWERCASE_CHARS_COUNT,MIN_UPPERCASE_CHARS_COUNT,MIN_NUMERIC_COUNT) values (30, 25, 1, 0, 7, 10, 3001,1,1,1);
insert into lockout_policies(APPLICATION_ID,DURATION,THRESHOLD,RESET_TIME,ATTEMPT_WINDOW) values (3001,NULL,3,NULL,10);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3001,'Sample Group 3001','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3002,'Sample Group 3002','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3003,'Sample Group 3003','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3004,'Sample Group 3004','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3005,'Sample Group 3005','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3001,'Authority 3001','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3002,'Authority 3002','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3003,'Authority 3003','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3004,'Authority 3004','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3005,'Authority 3005','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3006,'Authority 3006','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3007,'Authority 3007','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3008,'Authority 3008','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3009,'Authority 3009','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (3010,'Authority 3010','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3002,3003);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3003,3006);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3003,3007);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3003,3008);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3004,3006);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3004,3007);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (3005,3009);
commit;