insert into applications(id,name,description,creation_date,last_update_date,version) values (3001,'Test Application 1','This application is used for testing.',current_timestamp(),current_timestamp(),1);
insert into password_policies(id,max_age, max_length, min_special_chars_count, min_age, min_length, history_threshold, application_id,min_lowercase_chars_count,min_uppercase_chars_count,min_numeric_count,creation_date,last_update_date,version) values (3001,30, 25, 1, 0, 7, 10, 3001,1,1,1,current_timestamp(),current_timestamp(),1);
insert into lockout_policies(id,application_id,duration,threshold,reset_time,attempt_window,creation_date,last_update_date,version) values (3001,3001,NULL,3,NULL,10,current_timestamp(),current_timestamp(),1);
insert into groups(id,name,description,application_id,creation_date,last_update_date,version) values (3001,'Sample Group 3001','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(id,name,description,application_id,creation_date,last_update_date,version) values (3002,'Sample Group 3002','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(id,name,description,application_id,creation_date,last_update_date,version) values (3003,'Sample Group 3003','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(id,name,description,application_id,creation_date,last_update_date,version) values (3004,'Sample Group 3004','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into groups(id,name,description,application_id,creation_date,last_update_date,version) values (3005,'Sample Group 3005','Group description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3001,'Authority 3001','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3002,'Authority 3002','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3003,'Authority 3003','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3004,'Authority 3004','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3005,'Authority 3005','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3006,'Authority 3006','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3007,'Authority 3007','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3008,'Authority 3008','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3009,'Authority 3009','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into authorities(id,name,description,application_id,creation_date,last_update_date,version) values (3010,'Authority 3010','Authority description',3001,current_timestamp(),current_timestamp(),1);
insert into group_authorities(group_id,authority_id) values (3002,3003);
insert into group_authorities(group_id,authority_id) values (3003,3006);
insert into group_authorities(group_id,authority_id) values (3003,3007);
insert into group_authorities(group_id,authority_id) values (3003,3008);
insert into group_authorities(group_id,authority_id) values (3004,3006);
insert into group_authorities(group_id,authority_id) values (3004,3007);
insert into group_authorities(group_id,authority_id) values (3005,3009);
commit;