insert into applications(ID,NAME,DESCRIPTION,creation_date,last_update_date,version) values (5001,'Test Application 1','This application is used for testing.',current_timestamp(),current_timestamp(),1);
insert into password_policies(MAX_AGE, MAX_LENGTH, MIN_SPECIAL_CHARS_COUNT, MIN_AGE, MIN_LENGTH, HISTORY_THRESHOLD, APPLICATION_ID,MIN_LOWERCASE_CHARS_COUNT,MIN_UPPERCASE_CHARS_COUNT,MIN_NUMERIC_COUNT) values (30, 25, 1, 0, 7, 10, 5001,1,1,1);
insert into lockout_policies(APPLICATION_ID,DURATION,THRESHOLD,RESET_TIME,ATTEMPT_WINDOW) values (5001,NULL,3,NULL,10);
insert into users(ID,LAST_ACTIVITY_DATE,USER_NAME,APPLICATION_ID,CREATION_DATE,LAST_UPDATE_DATE,VERSION) values (5001, '1754-01-01', 'sampleUser1', 5001,current_timestamp(),current_timestamp(),1);
insert into memberships(ENABLED,CREATION_DATE,DESCRIPTION,FAILED_REVRY_ATMPT_CNT,FAILED_REVRY_ATMPT_WIN_START,FAILED_PWD_ATMPT_CNT,FAILED_PWD_ATMPT_WIN_START,LAST_LOCK_OUT_DATE,LAST_PWD_CHANGE_DATE,LOCKED,PASSWORD,USER_ID,ENCRYPTED) values (1, current_timestamp(), 'Description of membership', 0, '1754-01-01', 0, '1754-01-01', '1754-01-01', current_timestamp(), 0, 'admin', 5001, 0);
insert into groups(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (5001,'Group 1','Group description',5001,current_timestamp(),current_timestamp(),1);
insert into authorities(ID,NAME,DESCRIPTION,APPLICATION_ID,creation_date,last_update_date,version) values (5001,'Authority 1','Authority description',5001,current_timestamp(),current_timestamp(),1);
insert into group_authorities(GROUP_ID,AUTHORITY_ID) values (5001,5001);
insert into group_users(USER_ID,GROUP_ID) values (5001,5001);
insert into recovery_information(ID,USER_ID,QUESTION,ANSWER,ENCRYPTED,CREATION_DATE,LAST_UPDATE_DATE,VERSION) values (5001,5001,'What is your father''s tribe?','SAMPLE FATHER''S TRIBE',0,current_timestamp(),current_timestamp(),1);
insert into recovery_information(ID,USER_ID,QUESTION,ANSWER,ENCRYPTED,CREATION_DATE,LAST_UPDATE_DATE,VERSION) values (5002,5001,'What is your dream work?','SAMPLE DREAM WORK',0,current_timestamp(),current_timestamp(),1);
insert into recovery_information(ID,USER_ID,QUESTION,ANSWER,ENCRYPTED,CREATION_DATE,LAST_UPDATE_DATE,VERSION) values (5003,5001,'What was the name of your primary school?','SAMPLE PRIMARY SCHOOL NAME',0,current_timestamp(),current_timestamp(),1);
insert into login_histories(USER_ID,HISTORY_ID,LOGIN_DATE) values (5001,1,current_timestamp());
commit;